# Generated by Django 4.1.5 on 2023-04-16 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catProf', models.CharField(default='admin', max_length=50, verbose_name='Заказчик')),
                ('nameCart', models.CharField(max_length=200, verbose_name='Название')),
                ('imageCart', models.ImageField(blank=True, upload_to='catalog/')),
                ('textCart', models.TextField(verbose_name='Краткое описание')),
                ('metka', models.BooleanField(default=True, verbose_name='Гражданский')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
